In [1]:
import tensorflow as tf

x = tf.placeholder("float", None)
y = x * 2

with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1, 2, 3]})
    print(result)

[2. 4. 6.]


/opt/ds/lib/python3.4/importlib/_bootstrap.py:321: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  return f(*args, **kwds)


In [3]:
import tensorflow as tf

x = tf.placeholder("float", [None, 3])
y = x * 2

with tf.Session() as session:
    x_data = [[1, 2, 3],
              [4, 5, 6],]
    result = session.run(y, feed_dict={x: x_data})
    print(result)
    
tf.get_default_graph().get_operations()

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


[<tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'Placeholder_1' type=Placeholder>,
 <tf.Operation 'mul_1/y' type=Const>,
 <tf.Operation 'mul_1' type=Mul>,
 <tf.Operation 'Placeholder_2' type=Placeholder>,
 <tf.Operation 'mul_2/y' type=Const>,
 <tf.Operation 'mul_2' type=Mul>]