In [2]:
import tensorflow as tf

# I create a first Tensor with a defined shape
my_tensor = tf.constant(0, shape=[6,2])
my_static_shape = my_tensor.get_shape()
print(my_static_shape) 


(6, 2)


In [3]:
# Let's do an operation resulting in a new tensor
my_tensor_transposed = tf.transpose(my_tensor)
print(my_tensor_transposed.get_shape()) 

(2, 6)


In [4]:
# At any moment, you can also force a Tensor with an undefined (None) dimension
# to have a precise shape of the same rank.
# It might be needed if the shape can't be inferred from the graph alone (dynamic input data...)
my_placeholder = tf.placeholder(tf.float32, shape=[None, 2])
print(my_placeholder.get_shape()) 

(?, 2)


In [6]:
#If we add a scalar, the results are fairly predictable
a = tf.constant([[1, 2, 3], [4, 5, 6]], name='a')
b = tf.constant(100, name='b')
add_op = a + b

with tf.Session() as session:
    print(session.run(add_op))

[[101 102 103]
 [104 105 106]]


In [7]:
a = tf.constant([[1, 2, 3], [4, 5, 6]], name='a')
b = tf.constant([[1, 2, 3], [4, 5, 6]], name='b')
add_op = a + b

with tf.Session() as session:
    print(session.run(add_op))

[[ 2  4  6]
 [ 8 10 12]]


In [5]:
#what happens if we add a one-dimensional array to a two-dimensional matrix
a = tf.constant([[1, 2, 3], [4, 5, 6]], name='a')
b = tf.constant([100, 101, 102], name='b')
add_op = a + b

with tf.Session() as session:
    print(session.run(add_op))

[[101 103 105]
 [104 106 108]]
